### ISSUE TITLE
Zoznam výdavkov - Úprava položiek v zozname

### ISSUE THREAD

**Issue by RichardFedak** [RichardFedak/tva#18]
Ak zadám pre výdavok veľmi dlhý popis, tak sa celý popis zobrazí v zozname, bolo by dobré dať nejaký limit a potom zobraziť napr. tri bodky.

Pre každý výdavok by som navrhoval zobraziť rovnako aj kategóriu. (Momentálne sa zobrazuje len čiastka a popis)

**Comment by milantru** [comment]
Čo keby sme namiesto vypísania názvu kategórie zmenili farbu riadka podľa kategórie? Napr. ak ide o kategóriu Food, tak by bol riadok červený, ak by mal výdavok kategóriu Fun, bol by napr. modrý. Hm?
