### ISSUE TITLE
String resources

### ISSUE THREAD

**Issue by RichardFedak** [RichardFedak/tva#19]
V celej aplikácií sa nachádzajú miesta s hardcoded textom, je potrebné pridať pre ne string resources

**Comment by milantru** [comment]
Nejaké string resources sa pridali (pomocou Pull Requestu, preto sa issue zatvorilo), ale bolo by dobré neskôr prejsť celú aplikáciu a nájsť stringy, ktoré by sa presunuli do string resources - preto som toto issue otvoril znovu.
