### ISSUE TITLE
Nepoužívať `allowMainThreadQueries`

### ISSUE THREAD

**Issue by milantru** [RichardFedak/tva#30]
V triede `TvaBaseViewModel` sa využíva metóda `allowMainThreadQueries`. Toto asi nie je najlepšie riešenie, nakoľko to vraj môže sposobiť zaseknutie aplikácie (viď [odkaz](https://stackoverflow.com/questions/52999851/why-is-recommended-not-to-use-allowmainthreadqueries-for-android-room)). Bolo by vhodné túto metódu zmazať a využiť `suspend`.

**Comment by RichardFedak** [comment]
Suspend by trebalo asi využiť aj pre Dao funkcie ?

**Comment by milantru** [comment]
Aj tam sa pridajú, áno.
